server:
  port: 8085

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
  datasource:
    username: postwoman
    password: postwoman
    url: "jdbc:postgresql://localhost:5432/postwoman"
me:
  mahdiyar:
    services:
      token:
        age: 40